app/urls.py
from django.contrib import admin
from django.urls import path, include

from app import settings
from core.homepage.views import IndexView
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from core.login.views import *

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('admin/', admin.site.urls),
    path('erp/', include('core.erp.urls')),
    path('login/', include('core.login.urls')),
    path('user/', include('core.user.urls')),
    path('reports/', include('core.reports.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    # path("ckeditor5/", include('django_ckeditor_5.urls'), name="ck_editor_5_upload_file"),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/erp/urls.py
from django.urls import path

from core.erp.views.dashboard.views import DashboardView
from core.erp.views.department.views import *
from core.erp.views.letter.views import LetterMyListView, LetterCreateView, ReferenceSearchView, \
    LetterUpdateView, LetterListView, LetterApproveView, ExportarCartaPDF, DownloadProtocolView, \
    LetterDetailView
from core.erp.views.reference.views import ReferenceListView, ReferenceCreateView, ReferenceDeleteView
from core.erp.views.type.views import *
from core.erp.views.position.views import *
from core.erp.views.absence.views import *

from django.conf.urls.static import static

app_name = 'erp'
urlpatterns = [
    # department
    path('department/list/', DepartmentListView.as_view(), name='department_list'),
    path('department/add/', DepartmentCreateView.as_view(), name='department_create'),
    path('department/update/<int:pk>/', DepartmentUpdateView.as_view(), name='department_update'),
    path('department/delete/<int:pk>/', DepartmentDeleteView.as_view(), name='department_delete'),
    path('department/form/', DepartmentFormView.as_view(), name='department_form'),

    # position
    path('position/list/', PositionListView.as_view(), name='position_list'),
    path('position/add/', PositionCreateView.as_view(), name='position_create'),
    path('position/update/<int:pk>/', PositionUpdateView.as_view(), name='position_update'),
    path('position/delete/<int:pk>/', PositionDeleteView.as_view(), name='position_delete'),

    # type
    path('type/list/', TypeListView.as_view(), name='type_list'),
    path('type/add/', TypeCreateView.as_view(), name='type_create'),
    path('type/update/<int:pk>/', TypeUpdateView.as_view(), name='type_update'),
    path('type/delete/<int:pk>/', TypeDeleteView.as_view(), name='type_delete'),

    # Absence
    path('absence/list/', AbsenceListView.as_view(), name='absence_list'),
    path('absence/my/list/', MyAbsenceListView.as_view(), name='absence_my_list'),
    path('absence/add/', AbsenceCreateView.as_view(), name='absence_create'),
    #path('Absence/add/', PedidoAusenciaView.as_view(), name='Absence_create'),
    path('absence/update/<int:pk>/', AbsenceUpdateView.as_view(), name='absence_update'),
    path('absence/delete/<int:pk>/', AbsenceDeleteView.as_view(), name='absence_delete'),
    # pending aprove
    path('absence/aprove/<int:pk>/', AproveUpdateAbsenceView.as_view(), name='absence_update_aprove'),
    path('absence/aprove/manager/<int:pk>/', AproveUpdateManagerAbsenceView.as_view(), name='absence_update_aprove_manager'),
    path('absence/aprove/', AproveCreateAbsenceView.as_view(), name='absence_create_aprove'),
    # Print Absence
#    path('absence/print/pdf/<int:pk>/', AbsenceInfoPdf.as_view(), name='absence_print_pdf'),
    path('absence/print/pdf/<int:pk>/', GeneratePdf.as_view(), name='absence_print_pdf'),
    path('absence/view/pdf/<int:pk>/', AbsenceViewPdf.as_view(), name='view_pdf'),
    # dashboard
    path('dashboard/', DashboardView.as_view(), name='dashboard'),

    path('reference/list/', ReferenceListView.as_view(), name='reference_list'),
    path('reference/add/', ReferenceCreateView.as_view(), name='reference_create'),
    path('department/update/<int:pk>/', DepartmentUpdateView.as_view(), name='department_update'),
    path('reference/delete/<int:pk>/',ReferenceDeleteView.as_view(), name='reference_delete'),
    path('department/form/', DepartmentFormView.as_view(), name='department_form'),

    path('reference/search/', ReferenceSearchView.as_view(), name='reference_search'),
    #path('reference/check/', LetterCheckView.as_view(), name='reference_check'),
    path('letter/add/', LetterCreateView.as_view(), name='letter_create'),
    path('letter/update/<int:pk>/', LetterUpdateView.as_view(), name='letter_update'),
    path('letter/approve/<int:pk>/', LetterApproveView.as_view(), name='letter_approve'),
    path('letter/download/<int:pk>/', ExportarCartaPDF.as_view(), name='letter_download'),
    path('letter/mylist/', LetterMyListView.as_view(), name='letter_mylist'),
    path('letter/list/', LetterListView.as_view(), name='letter_list'),
    path('letter/detail/<int:pk>/', LetterDetailView.as_view(), name='letter_view'),
    path('create/', LetterCreateView.as_view(), name='create_letter'),
    path('letter/downloadprotocol/<int:pk>/', DownloadProtocolView .as_view(), name='download_protocol'),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/user/urls.py
from django.urls import path

from core.user.views import *

app_name = 'user'
urlpatterns = [
    # user
    path('list/', UserListView.as_view(), name='user_list'),
    path('add/', UserCreateView.as_view(), name='user_create'),
    path('update/<int:pk>/', UserUpdateView.as_view(), name='user_update'),
    path('delete/<int:pk>/', UserDeleteView.as_view(), name='user_delete'),
    path('change/group/<int:pk>/', UserChangeGroup.as_view(), name='user_change_group'),

]

core/erp/models.py
from datetime import datetime

from ckeditor.fields import RichTextField
from crum import get_current_user
from django.db import models
from django.forms import model_to_dict
from django_ckeditor_5.fields import CKEditor5Field

from app.settings import AUTH_USER_MODEL
from core.models import BaseModel
from app.util import *


class Department(models.Model):
    name = models.CharField(max_length=250, verbose_name='Nome', unique=True)
    abbreviation = models.CharField(max_length=70, verbose_name='Abreviatura', unique=True, null=True, blank=True)
    manager = models.OneToOneField(AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True,
                                   related_name='managed_department',
                                   verbose_name='Chefe de departamento')
    counter = models.IntegerField(default=0)
    desc = models.TextField(max_length=400, blank=True, verbose_name='Descrição')

    def toJson(self):
        item = model_to_dict(self)
        if self.manager != None:
            item['manager'] = self.manager.get_full_name()
        return item

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'departamento'
        verbose_name_plural = 'departamentos'
        db_table = 'departamento'
        ordering = ['id']


class Reference(BaseModel):
    reference_code = models.CharField(max_length=250, unique=True, blank=True)
    user_department = models.CharField(max_length=250, blank=True, null=True)

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        user = get_current_user()
        if user is not None:
            if not self.pk:
                self.user_created = user
            else:
                self.user_updated = user

        super(Reference, self).save()

    def toJson(self):
        item = model_to_dict(self)
        item['date_created'] = self.date_created.strftime('%Y-%m-%d')
        item['user_created'] = self.user_created.get_full_name()
        return item

    def __str__(self):
        return self.reference_code

    class Meta:
        verbose_name = 'referencia'
        verbose_name_plural = 'referencias'
        db_table = 'referencia'
        ordering = ['id']


class Letter(BaseModel):
    letter_status = [
        ('', 'Selecione uma opção'),  # Primeira opção vazia
        ('drafted', 'Rascunho'),
        ('submitted', 'Submetida para Aprovação'),
        ('approved', 'Aprovada'),
        ('rejected', 'Rejeitada'),
        ('sent', 'Enviada'),
    ]
    reference_code = models.ForeignKey(Reference, max_length=250, on_delete=models.CASCADE, null=False, blank=False,
                                       verbose_name='Código de referência')
    recipient = models.CharField(max_length=200, blank=True, null=True,
                                 verbose_name='Destinatário')
    job = models.CharField(max_length=200, blank=True, null=True,
                           verbose_name='Função')
    city = models.CharField(max_length=200, blank=True, null=True,
                            verbose_name='Cidade')

    entity = models.CharField(max_length=200, blank=True, null=True,
                              verbose_name='Entidade')

    title = models.CharField(max_length=255, blank=True, null=True,
                             verbose_name='Assunto')
    content = RichTextField(blank=True, null=True)

    department = models.ForeignKey('Department', on_delete=models.CASCADE)

    date_sent = models.DateTimeField(
        verbose_name='Data de expedição')
    status = models.CharField(max_length=20, choices=letter_status, default=letter_status[0][0], blank=False,
                              null=False,
                              verbose_name='Estado')

    coment_rejected = models.TextField(blank=True, null=True, verbose_name='Comentário de rejeição')
    coment_review = models.TextField(blank=True, null=True, verbose_name='Comentário de revisão')
    protocol = models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Protocolo')

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        previous_status = None
        if self.pk:  # Se a carta já existe, pegamos o status anterior
            previous_status = Letter.objects.get(pk=self.pk).status
        user = get_current_user()
        if user is not None:
            if not self.pk:
                self.user_created = user
            else:
                self.user_updated = user

        super(Letter, self).save()

        # Verifica se a carta foi submetida
        if previous_status != 'submitted' and self.status == 'submitted':
            send_submission_email(self)

        # Verifica se a carta foi aprovada ou rejeitada
        if previous_status != self.status and self.status in ['approved', 'rejected']:
            send_approval_rejection_email(self)

            # Verifica se a carta foi enviada
            if previous_status != 'sent' and self.status == 'sent':
                send_letter_sent_email_with_attachment(self)  # Chama a função do util.py para enviar o e-mail com anexo

    def get_status_display(self):
        # Procura no `letter_status` a tupla onde a chave bate com o valor atual de status
        for key, display_value in self.letter_status:
            if self.status == key:
                return display_value
        return None  # Retorna None se não encontrar o valor

    def toJson(self):
        item = model_to_dict(self, exclude='protocol')
        item['date_sent'] = self.date_sent.strftime('%Y-%m-%d')
        item['reference_code'] = self.reference_code.reference_code
        item['date_created'] = self.date_created.strftime('%Y-%m-%d')
        item['date_updated'] = self.date_created.strftime('%Y-%m-%d')
        item['user_created'] = self.user_created.get_full_name()
        item['status_desc'] = self.get_status_display()
        item['department_name'] = self.department.name
        return item

    def __str__(self):
        return str(self.id)

    class Meta:
        verbose_name = 'carta'
        verbose_name_plural = 'cartas'
        db_table = 'carta'
        ordering = ['id']

core/user/models.py
from datetime import timedelta, date

from crum import get_current_request
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.db.models import Sum, F, DurationField
from django.forms import model_to_dict
from app.settings import MEDIA_URL, STATIC_URL
from core.erp.models import Department
from core.homepage.models import Absence, Position


class User(AbstractUser):
    image = models.ImageField(upload_to='users/%Y%m%d', blank=True, null=True)
    max_days_year = models.PositiveIntegerField(default=22, blank=True, null=True)
    available_days = models.PositiveIntegerField(default=0, blank=True, null=True)
    used_days = models.PositiveIntegerField(default=0, blank=True, null=True)
    hold_days = models.PositiveIntegerField(default=0, blank=True, null=True)

    department = models.ForeignKey(Department, on_delete=models.CASCADE, blank=True, null=True, verbose_name='Departamento')
    position = models.ForeignKey(Position, on_delete=models.CASCADE, blank=True, null=True, verbose_name='Cargo')


    def get_image(self):
        if self.image:
            return '{}{}'.format(MEDIA_URL, self.image)
        return '{}{}'.format(STATIC_URL, 'img/empty.png')

    def toJSON(self):
        item = model_to_dict(self, exclude=['password', 'user_permissions', 'last_login'])
        if self.last_login:
            item['last_login'] = self.last_login.strftime('%Y-%m-%d')
        item['date_joined'] = self.date_joined.strftime('%Y-%m-%d')
        item['image'] = self.get_image()
        print(self.department)
        item['department'] = self.department.toJson()
        item['position'] = self.position.toJson()

        item['full_name'] = self.get_full_name()
        item['groups'] = [{'id': g.id, 'name': g.name} for g in self.groups.all()]
        print(item)
        return item

    def get_group_session(self):
        try:
            request = get_current_request()
            groups = self.groups.all()
            if groups.exists():
                if 'group' not in request.session:
                    request.session['group'] = groups[0]
        except:
            pass


    def save(self, *args, **kwargs):
        super().save()


    def atualizar_ferias_anuais(self):
        # Calcula o total de dias de ausência aprovados para o usuário
        total_ausencias_aprovadas = Absence.objects.filter(
            User=self.user, status='Aprovado'
        ).aggregate(total_dias=Sum(F('end_date') - F('start_date'), output_field=DurationField()))[
                                        'total_dias'] or timedelta(days=0)

        # Considera o limite máximo de 22 dias por ano
        # dias_maximos_por_ano = 22

        # Calcula os dias acumulados do ano anterior (se houver)
        dias_acumulados_anterior = self.available_days - self.max_days_year
        if dias_acumulados_anterior < 0:
            dias_acumulados_anterior = 0

        # Atualiza o saldo de férias anuais
        self.available_days = max(0,
                                  dias_acumulados_anterior + self.max_days_year - total_ausencias_aprovadas.days)
        self.save()

    def calcular_dias_disponiveis(self):
        total_available_days = self.available_days
        ano_atual = date.today().year
        ausencias_ano_atual = Absence.objects.filter(data_inicio__year=ano_atual, User=self.user, status='Aprovado')
        for ausencia in ausencias_ano_atual:
            total_available_days -= (ausencia.end_date - ausencia.start_date).days
        self.available_days = max(0, total_available_days)
        self.save()

    def notificacao_ferias_seis_meses(self):
        # Calcula a data há 6 meses atrás
        data_seis_meses_atras = date.today() - timedelta(days=180)

        # Filtra as ausências nos últimos 6 meses
        ausencias_seis_meses = Absence.objects.filter(data_inicio__gte=data_seis_meses_atras)

        # Calcula o total de dias de ausência nos últimos 6 meses
        total_dias_ausencia_seis_meses = sum(
            (ausencia.end_date - ausencia.start_date).days + 1 for ausencia in ausencias_seis_meses)

        # Calcula os dias disponíveis de férias atualmente
        dias_disponiveis = self.calcular_dias_disponiveis()

        # Verifica se o funcionário tem mais de 22 dias de férias disponíveis após 6 meses
        if total_dias_ausencia_seis_meses == 0 and dias_disponiveis > 22:
            # Envia a notificação para o funcionário
            Notification.objects.create(
                funcionario=self,
                mensagem=f"Você tem mais de 22 dias de férias disponíveis após 6 meses. Por favor, planeje suas férias."
            )

    def __str__(self):
        return self.get_full_name()

class Notification(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    mensagem = models.TextField()
    lida = models.BooleanField(default=False)
    criado_em = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.mensagem

templates/vtc/body.html
{% extends 'home.html' %}
{% block body %}
    <body class="hold-transition sidebar-mini layout-fixed">
    <div class="wrapper">
        <!-- Header -->
        {% include 'vtc/header.html' %}
        <!-- Sidebar -->
        {% include 'vtc/sidebar.html' %}
        <!-- Content -->
        <div class="content-wrapper">
            <div class="content-header">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-sm-6">
                            <h1 class="m-0 text-dark"> Benvindo <small>{{ request.user.get_full_name }}</small></h1>
                        </div>
                        <div class="col-sm-6">
                            <ol class="breadcrumb float-sm-right">
                                <li class="breadcrumb-item"><a href="#">Home</a></li>
                                <li class="breadcrumb-item"><a href="{{ list_url }}">{{ entity }}</a></li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content">
                <div class="container-fluid">
                    {% block content %}

                    {% endblock %}
                </div>
            </div>
        </div>
        <!-- Footer -->
        {% include 'footer.html' %}
    </div>
    <!-- Block javascript -->
    {% block javascript %}

    {% endblock %}
    <script>
        {% if messages %}
            var html = '<p>';
            {% for message in messages %}
                html += '{{ message }}<br>';
            {% endfor %}
            html += '</p>';
            Swal.fire({
                title: 'Erro!',
                html: html,
                icon: 'error'
            });
        {% endif %}
    </script>
    </body>
{% endblock %}

templates/vtc/header.html
<nav class="main-header navbar navbar-expand navbar-dark navbar-primary">
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="#" class="nav-link">Home</a>
        </li>
    </ul>
    <ul class="navbar-nav ml-auto">
        {% if request.user.groups.all %}
            <li class="nav-item dropdown">
                    <a id="dropdownSubMenu1" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
                       class="nav-link  {% if request.user.groups.all.count > 1 %} dropdown-toggle {% endif %}">{{ request.session.group }}</a>
                    {% if request.user.groups.all.count > 1 %}
                        <ul aria-labelledby="dropdownSubMenu1" class="dropdown-menu border-0 shadow"
                            style="left: 0px; right: inherit;">
                            {% for g in request.user.groups.all %}
                                {% if g.id != request.session.group.id %}
                                    <li><a href="{% url 'user:user_change_group' g.id %}"
                                           class="dropdown-item">{{ g.name }}</a></li>
                                {% endif %}
                            {% endfor %}
                        </ul>
                    {% endif %}
                </li>

        {% endif %}
        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="fas fa-users-cog"></i>{{ request.user.username }}
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                    <span class="dropdown-header" style="font-size: 12px;">
                        Seu último acceso foi {{ request.user.last_login }}
                    </span>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fas fa-edit mr-2"></i> Editar perfil
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fas fa-lock mr-2"></i> Editar password
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item dropdown-footer">
                    <p>Este sistema te permitirá realizar diferentes actividades</p>
                </a>
            </div>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">
                <i class="fas fa-power-off" aria-hidden="true"></i>
            </a>
        </li>
    </ul>
</nav>

templates/vtc/sidebar.html
{% load static %}
<aside class="main-sidebar sidebar-light-primary elevation-4">
    <a href="#" class="brand-link">
        <!--        <img src="{% static 'img/' %}"-->
        <!--             alt="Logo"-->
        <!--             class="brand-image img-circle elevation-3"-->
        <!--             style="opacity: .8">-->
        <!--        <span class="brand-text font-weight-light">Hades</span>-->
    </a>
    <div class="sidebar">
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">

                <img src="{{ request.user.get_image }}" class="img-circle" alt="User Image">
            </div>
            <div class="info">
                <a href="#" class="d-block">{{ request.user.username }}</a>
            </div>
        </div>
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <li class="nav-header">Módulos</li>
                {% if perms.homepage.view_position %}
                <li class="nav-item">
                    <a href="{% url 'erp:position_list' %}" class="nav-link">
                        <i class="fa fa-sitemap"></i>
                        <p>
                            Cargos
                        </p>
                    </a>
                </li>
                {% endif %}
                {% if perms.erp.view_department %}
                <li class="nav-item">
                    <a href="{% url 'erp:department_list' %}" class="nav-link">
                        <i class="fas fa-boxes"></i>
                        <p>
                            Departamentos
                        </p>
                    </a>
                </li>
                {% endif %}

                <!--                {% if perms.homepage.view_type %}-->
                <!--                <li class="nav-item">-->
                <!--                    <a href="{% url 'erp:type_list' %}" class="nav-link">-->
                <!--                         <i class=" fa fa-solid fa-envelope fa-bounce" ></i>-->
                <!--                         <i class="fa fa-ticket" ></i>-->
                <!--                        <i class="fa fa-ticket" aria-hidden="true"></i>-->

                <!--                        <p>-->
                <!--                             Motivos-->
                <!--                        </p>-->
                <!--                    </a>-->
                <!--                </li>-->
                <!--                {% endif %}-->

                <!--                {% if perms.homepage.aprove_absence %}-->
                <!--                <li class="nav-item">-->
                <!--                    <a href="{% url 'erp:absence_list' %}" class="nav-link">-->
                <!--                        <i class="fa fa-calendar"></i>-->
                <!--                        <p>-->
                <!--                           Ausências-->
                <!--                        </p>-->
                <!--                    </a>-->
                <!--                </li>-->
                <!--                {% endif %}-->

                <!--                <li class="nav-item">-->
                <!--                    <a href="{% url 'erp:absence_my_list' %}" class="nav-link">-->
                <!--                        <i class="fa fa-calendar"></i>-->
                <!--                        <p>-->
                <!--                          Minhas Ausências-->
                <!--                        </p>-->
                <!--                    </a>-->
                <!--                </li>-->


                {% if perms.user.view_user %}
                <li class="nav-item">
                    <a href="{% url 'user:user_list' %}" class="nav-link">
                        <i class="fas fa-users"></i>
                        <p>
                            Colaboradores
                        </p>
                    </a>
                </li>
                {% endif %}


                <li class="nav-item">
                    <a href="{% url 'erp:reference_list' %}" class="nav-link">
                      <i class="fa-brands fa-keycdn"></i>
                        <p>
                            Códigos de Referencias
                        </p>
                    </a>
                </li>

                <li class="nav-item">
                    <a href="{% url 'erp:letter_mylist' %}" class="nav-link">
                      <i class="fa-regular fa-envelope"></i>
                        <p>
                            Minhas Cartas
                        </p>
                    </a>
                </li>

                {% for g in request.user.groups.all %}
                {% if g.name != 'COLABORADOR' %}
                <li class="nav-item">
                    <a href="{% url 'erp:letter_list' %}" class="nav-link">
                       <i class="fa-solid fa-envelopes-bulk"></i>
                        <p>
                            Todas as Cartas
                        </p>
                    </a>
                </li>
                {% endif %}
                {% endfor %}

                 <li class="nav-item">
                    <a href="{% url 'letter_report' %}" class="nav-link">
                      <i class="fa-solid fa-filter"></i>
                        <p>
                          Reportes
                        </p>
                    </a>
                </li>

                <li class="nav-item">
                    <a href="{% url 'erp:dashboard' %}" class="nav-link">
                        <i class="nav-icon fas fa-chart-bar"></i>
                        <p>
                            Dashoboard
                        </p>
                    </a>
                </li>

            </ul>
        </nav>
    </div>
</aside>