app/urls.py
from django.contrib import admin
from django.urls import path, include

from app import settings
from core.homepage.views import IndexView
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from core.login.views import *

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('admin/', admin.site.urls),
    path('erp/', include('core.erp.urls')),
    path('login/', include('core.login.urls')),
    path('user/', include('core.user.urls')),
    path('reports/', include('core.reports.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    # path("ckeditor5/", include('django_ckeditor_5.urls'), name="ck_editor_5_upload_file"),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/erp/urls.py
from django.urls import path

from core.erp.views.dashboard.views import DashboardView
from core.erp.views.department.views import *
from core.erp.views.letter.views import LetterMyListView, LetterCreateView, ReferenceSearchView, \
    LetterUpdateView, LetterListView, LetterApproveView, ExportarCartaPDF, DownloadProtocolView, \
    LetterDetailView
from core.erp.views.reference.views import ReferenceListView, ReferenceCreateView, ReferenceDeleteView
from core.erp.views.type.views import *
from core.erp.views.position.views import *
from core.erp.views.absence.views import *

from django.conf.urls.static import static

app_name = 'erp'
urlpatterns = [
    # department
    path('department/list/', DepartmentListView.as_view(), name='department_list'),
    path('department/add/', DepartmentCreateView.as_view(), name='department_create'),
    path('department/update/<int:pk>/', DepartmentUpdateView.as_view(), name='department_update'),
    path('department/delete/<int:pk>/', DepartmentDeleteView.as_view(), name='department_delete'),
    path('department/form/', DepartmentFormView.as_view(), name='department_form'),

    # position
    path('position/list/', PositionListView.as_view(), name='position_list'),
    path('position/add/', PositionCreateView.as_view(), name='position_create'),
    path('position/update/<int:pk>/', PositionUpdateView.as_view(), name='position_update'),
    path('position/delete/<int:pk>/', PositionDeleteView.as_view(), name='position_delete'),

    # type
    path('type/list/', TypeListView.as_view(), name='type_list'),
    path('type/add/', TypeCreateView.as_view(), name='type_create'),
    path('type/update/<int:pk>/', TypeUpdateView.as_view(), name='type_update'),
    path('type/delete/<int:pk>/', TypeDeleteView.as_view(), name='type_delete'),

    # Absence
    path('absence/list/', AbsenceListView.as_view(), name='absence_list'),
    path('absence/my/list/', MyAbsenceListView.as_view(), name='absence_my_list'),
    path('absence/add/', AbsenceCreateView.as_view(), name='absence_create'),
    #path('Absence/add/', PedidoAusenciaView.as_view(), name='Absence_create'),
    path('absence/update/<int:pk>/', AbsenceUpdateView.as_view(), name='absence_update'),
    path('absence/delete/<int:pk>/', AbsenceDeleteView.as_view(), name='absence_delete'),
    # pending aprove
    path('absence/aprove/<int:pk>/', AproveUpdateAbsenceView.as_view(), name='absence_update_aprove'),
    path('absence/aprove/manager/<int:pk>/', AproveUpdateManagerAbsenceView.as_view(), name='absence_update_aprove_manager'),
    path('absence/aprove/', AproveCreateAbsenceView.as_view(), name='absence_create_aprove'),
    # Print Absence
#    path('absence/print/pdf/<int:pk>/', AbsenceInfoPdf.as_view(), name='absence_print_pdf'),
    path('absence/print/pdf/<int:pk>/', GeneratePdf.as_view(), name='absence_print_pdf'),
    path('absence/view/pdf/<int:pk>/', AbsenceViewPdf.as_view(), name='view_pdf'),
    # dashboard
    path('dashboard/', DashboardView.as_view(), name='dashboard'),

    path('reference/list/', ReferenceListView.as_view(), name='reference_list'),
    path('reference/add/', ReferenceCreateView.as_view(), name='reference_create'),
    path('department/update/<int:pk>/', DepartmentUpdateView.as_view(), name='department_update'),
    path('reference/delete/<int:pk>/',ReferenceDeleteView.as_view(), name='reference_delete'),
    path('department/form/', DepartmentFormView.as_view(), name='department_form'),

    path('reference/search/', ReferenceSearchView.as_view(), name='reference_search'),
    #path('reference/check/', LetterCheckView.as_view(), name='reference_check'),
    path('letter/add/', LetterCreateView.as_view(), name='letter_create'),
    path('letter/update/<int:pk>/', LetterUpdateView.as_view(), name='letter_update'),
    path('letter/approve/<int:pk>/', LetterApproveView.as_view(), name='letter_approve'),
    path('letter/download/<int:pk>/', ExportarCartaPDF.as_view(), name='letter_download'),
    path('letter/mylist/', LetterMyListView.as_view(), name='letter_mylist'),
    path('letter/list/', LetterListView.as_view(), name='letter_list'),
    path('letter/detail/<int:pk>/', LetterDetailView.as_view(), name='letter_view'),
    path('create/', LetterCreateView.as_view(), name='create_letter'),
    path('letter/downloadprotocol/<int:pk>/', DownloadProtocolView .as_view(), name='download_protocol'),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/erp/views/absence/views.py
import os
from io import BytesIO

from django.shortcuts import render
from weasyprint import HTML, CSS
from django.template.loader import get_template
from django.conf import settings
from django.http import HttpResponse

from django.contrib.staticfiles import finders

from crum import get_current_user
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

from django.http import JsonResponse, HttpResponseRedirect

from django.urls import reverse_lazy
from django.views import View
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, TemplateView
from django.utils.decorators import method_decorator

from core.erp.forms import AbsenceForm, AbsenceAdminForm
from core.erp.mixins import ValidatePermissionRequiredMixin

from core.homepage.models import Absence
from core.user.models import User


class AbsenceListView(LoginRequiredMixin, ValidatePermissionRequiredMixin, ListView):
    model = Absence
    template_name = 'Absence/list.html'
    permission_required = 'homepage.aprove_absence'

    @method_decorator(csrf_exempt)
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'searchdata':
                data = []
                chefe_departamento = request.user.department.manager  # Supondo que o usuário esteja autenticado como chefe de departamento

                if chefe_departamento.department is not None:
                    departamento = chefe_departamento.department
                    todas_ausencias = ""
                    if chefe_departamento == request.user:

                        # 2. Em seguida, filtre os usuários que pertencem ao mesmo departamento, mas não são o próprio chefe:
                        usuarios_departamento = User.objects.filter(department=departamento).exclude(
                            id=chefe_departamento.id)

                        # 3. Agora, obtenha todas as ausências (Absence) dos usuários do departamento, excluindo o chefe:
                        todas_ausencias = Absence.objects.filter(user_created__in=usuarios_departamento)

                        # 4. Você pode iterar sobre "todas_ausencias" para processar os dados conforme necessário.

                        if departamento == "":
                            todas_ausencias = Absence.objects.filter(status='PENDENTE')

                        for i in todas_ausencias:
                            data.append(i.toJson())
            else:
                data['error'] = 'Ocorreu um erro na requisição'
        except Exception as e:
            print(e)
            data['error'] = str(e)
        return JsonResponse(data, safe=False)

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        context["title"] = 'Lista de Ausências'
        context["create_url"] = reverse_lazy('erp:Absence_create')
        context["list_url"] = reverse_lazy('erp:absence_list')
        context["table"] = 'Absence'
        # context["action"] = 'searchdata'
        # context['departments'] = Department.objects.all()
        return context


class MyAbsenceListView(LoginRequiredMixin, ValidatePermissionRequiredMixin, ListView):
    model = Absence
    template_name = 'Absence/my.html'
    permission_required = 'homepage.view_absence'

    @method_decorator(csrf_exempt)
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):

        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'searchdata':
                data = []
                user = get_current_user()
                for i in Absence.objects.filter(user_created=user):
                    data.append(i.toJson())
            else:
                data['error'] = 'Ocorreu um erro na requisição'
        except Exception as e:
            print(e)
            data['error'] = str(e)
        return JsonResponse(data, safe=False)

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        context["title"] = 'Lista de Ausências'
        context["entity"] = 'Ausência'
        context["table"] = 'Absence'
        context["manager"] = 'NÃO'
        context['user'] = self.request.user
        # context["create_url"] = reverse_lazy('erp:Absence_create')
        # context["create_url"] = reverse_lazy('erp:Absence_create')
        context["list_url"] = reverse_lazy('erp:absence_my_list')


        # Verifique se o usuário é chefe de departamento (você precisará adaptar isso à sua lógica real)
        user_is_department_head = self.request.user.department.manager  # Exemplo hipotético

        if user_is_department_head == self.request.user:
            context["create_url"] = reverse_lazy('erp:absence_create_aprove')
            context["manager"] = 'SIM'
        else:
            context["create_url"] = reverse_lazy('erp:absence_create')
            context["manager"] = 'NÃO'
        return context


class AbsenceCreateView(LoginRequiredMixin, ValidatePermissionRequiredMixin, CreateView):
    model = Absence
    form_class = AbsenceForm
    template_name = 'Absence/create.html'
    success_url = reverse_lazy('erp:absence_list')
    #permission_required = 'homepage.aprove_absence'
    permission_required = 'homepage.view_absence'

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        self.object = None
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            if request.POST['action'] == 'add':
                form = self.get_form()
                data = form.save()
            else:
                data['error'] = 'Não escolheu nenhuma opção válida'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = 'Criar Ausências'
        context["entity"] = 'Ausências'
        context["table"] = 'Absence'
        context["action"] = 'add'
        context["list_url"] = reverse_lazy('erp:absence_my_list')
        context["create_url"] = reverse_lazy('erp:absence_create')
        return context


class AbsenceUpdateView(LoginRequiredMixin, ValidatePermissionRequiredMixin, UpdateView):
    model = Absence
    form_class = AbsenceForm
    template_name = 'Absence/create.html'
    success_url = reverse_lazy('erp:absence_list')
    #permission_required = 'homepage.aprove_absence'
    permission_required = 'homepage.view_absence'

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            if request.POST['action'] == 'edit':
                form = self.get_form()
                data = form.save()
            else:
                data['error'] = 'Não escolheu nenhuma opção válida'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = 'Editar Ausência'
        context["entity"] = 'Ausência'
        context["table"] = 'Absence'
        context["action"] = 'edit'
        context["list_url"] = reverse_lazy('erp:absence_my_list')
        context["edit_url"] = reverse_lazy('erp:absence_edit')
        return context


class AbsenceDeleteView(DeleteView):
    model = Absence
    template_name = 'Absence/delete.html'
    success_url = reverse_lazy('erp:absence_list')
    permission_required = 'homepage.delete_absence'

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()  # obtem o objeto que queremo eliminar
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            self.object.delete()  # eliminamos o objeto
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = 'Eliminar Ausência'
        context["entity"] = 'Ausência'
        context["table"] = 'Absence'
        # context["list_url"] = reverse_lazy('erp:Absence_list')
        context["list_url"] = reverse_lazy('erp:absence_my_list')
        context["remove_url"] = reverse_lazy('erp:absence_edit')
        return context


class AproveUpdateAbsenceView(UpdateView):
    model = Absence
    form_class = AbsenceAdminForm
    template_name = 'Absence/create.html'
    success_url = reverse_lazy('erp:absence_list')
    # success_url = reverse_lazy('erp:Absence_my_list')
    permission_required = 'homepage.aprove_absence'

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()

        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            if request.POST['action'] == 'edit':
                form = self.get_form()
                data = form.save()
            else:
                data['error'] = 'Não escolheu nenhuma opção válida'

core/erp/templates/letter/aproved.html
{% extends 'list.html' %}
{% load static %}
{% block  head_list %}
<script src="{% static 'absense/js/list.js' %}"></script>
{% endblock %}

{% block columns %}
<tr>
    <th scope="col" style="width: 10%">#</th>
    <th scope="col" style="width: 30%">Motivo</th>
    <th scope="col" style="width: 20%">Colaborador</th>
    <th scope="col" style="width: 20%">Data de Inicio</th>
    <th scope="col" style="width: 10%">Data de Fim</th>
    <th scope="col" style="width: 10%">Dias</th>
    <th scope="col" style="width: 10%">Estado</th>
    <th scope="col" style="width: 10%">Opções</th>
</tr>
{% endblock %}

{% block rows %}

{% endblock %}

{% block js %}
<script src="{% static 'absense/js/list.js' %}"></script>
{% endblock %}

core/erp/templates/letter/base_pdf.html
{% load static %}
<!doctype html>
<html lang="es">
    <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Reporte PDF</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <style>
        @page {
            size: "A4";
            margin: 1.0cm 1.5cm 3.5cm 1.5cm;
        }
        body {
            width: 100% !important;
            height: 100%;
            background: #fff;
            color: black;
            font-size: 100%;
            font-family: 'Roboto', sans-serif;
            line-height: 1.65;
            -webkit-font-smoothing: antialiased;
            -webkit-text-size-adjust: none;
        }

    </style>
</head>
<body>
<main class="container">
    {% block content %}
    {% endblock %}
</main>
</body>
</html>

core/erp/templates/letter/create.html
{% extends 'form.html' %}
{% load static %}
{% block head_form %}

<link href="{% static 'lib/jquery-ui-1.12.1/jquery-ui.min.css' %}" rel="stylesheet"/>
<script src="{% static 'lib/jquery-ui-1.12.1/jquery-ui.min.js' %}"></script>

<link href="{% static 'lib/select2-4.0.13/css/select2.min.css' %}" rel="stylesheet"/>
<link href="{% static 'lib/select2-4.0.13/css/select2-bootstrap4.min.css' %}" rel="stylesheet"/>
<script src="{% static 'lib/select2-4.0.13/js/select2.min.js' %}"></script>
<script src="{% static 'lib/select2-4.0.13/js/i18n/es.js' %}"></script>

<script src="{% static 'lib/moment-2.25.3/moment-with-locales.js' %}"></script>
<script src="{% static 'lib/tempusdominus-bootstrap-4/tempusdominus-bootstrap-4.min.js' %}"></script>
<link href="{% static 'lib/tempusdominus-bootstrap-4/tempusdominus-bootstrap-4.min.css' %}" rel="stylesheet"/>

<link href="{% static 'lib/bootstrap-touchspin-4.3.0/jquery.bootstrap-touchspin.css' %}" rel="stylesheet"/>
<script src="{% static 'lib/bootstrap-touchspin-4.3.0/jquery.bootstrap-touchspin.js' %}"></script>

<link href="{% static 'lib/select2-4.0.13/css/select2.min.css' %}" rel="stylesheet"/>
<link href="{% static 'lib/select2-4.0.13/css/select2-bootstrap4.min.css' %}" rel="stylesheet"/>
<script src="{% static 'lib/select2-4.0.13/js/select2.min.js' %}"></script>
<script src="{% static 'lib/select2-4.0.13/js/i18n/es.js' %}"></script>
<script src="{% static 'letter/js/form.js' %}"></script>
<link href="{% static 'letter/css/style.css' %}" rel="stylesheet"/>
{% endblock %}

{% block javascript %}
<script type="application/javascript">
    $(document).ready(function () {
        function errorValidation(input, message) {
            const formControl = input.parentElement;
            console.log(formControl, 'form g')
            const small = formControl.querySelector('small')
            console.log(small)
            small.innerText = message
            formControl.className = 'form-group error'

        }

        function successValidation(input) {
            const formControl = input.parentElement;
            formControl.className = 'form-group success'
        }

        const assunto = document.getElementById('id_reason');
        const data = document.getElementById('date_sent');


        function checkInputs() {
            const assuntoValue = document.getElementById('id_reason').value.trim();
            const dataValue = document.getElementById('date_sent').value.trim();


            console.log(dataValue, 'data')
            console.log(assuntoValue, 'assunto')

            let allgood = true;

            if (assuntoValue === "") {
                errorValidation(assunto, 'Preencha esse campo')
                allgood = false;
            } else {
                successValidation(assunto)
                allgood = true;
            }

            if (dataValue === "") {
                errorValidation(data, 'Preencha esse campo')
                allgood = false;
            } else {
                successValidation(data)
                allgood = true;
            }
            // if (textoSemTags === '') {
            //     alert("O campo de conteúdo não pode estar vazio.");
            //     errorValidation(corpo, 'Preencha esse campo')
            //     allgood = false;
            // } else {
            //     //successValidation(corpo)
            //     allgood = true;
            // }
            return allgood
        }

        var codigo_id = "{{ codigo_id|escapejs }}";
        var user_id = "{{ user_id|escapejs }}";
        var codigo = "{{ codigo|escapejs }}";
        var user = "{{ user|escapejs }}";


        // reference.selectedIndex = codigo_id;
        // reference.selected = codigo_id;
        // document.getElementById('reference_code').selected = codigo;
        // document.getElementById('reference_code').value = "";
        // var status = document.getElementById('status');
        // console.log(codigo_id, 'reference codigo')
        // console.log(document.getElementById('reference_code').selected, 'podes codigo selecionado')
        // document.getElementById('reference_code').selected =reference.value;


        $("#letter-form").on('submit', function (e) {
            e.preventDefault();
            var parameters = new FormData(this);
            console.log(parameters)
            console.log('xxxx')
            if (checkInputs()) {
                $.ajax({
                    delay: 250,
                    url: "{% url 'erp:letter_create' %}",  // Substitua pela URL correta
                    method: "POST",
                    data: $(this).serialize(),
                    dataType: "json",
                    success: function (response) {

                        console.log(response);
                    }
                });
            }
        });

        // $('#date_sent').datetimepicker({
        //     useCurrent: false,
        //     format: 'YYYY-MM-DD',
        //     //date: inicio.value,
        //     locale: 'pt',
        //     showButtonPanel: true,
        //     showTodayButton: true,
        //     keepOn: true,
        //
        // });

    });

</script>
{% endblock %}

core/erp/templates/letter/delete.html
{% extends 'delete.html' %}

core/erp/templates/letter/footer.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
dddddddddddddddddddddd
</body>
</html>

core/erp/templates/letter/list.html
{% extends 'list.html' %}
{% load static %}
{% block  head_list %}


<script src="{% static 'letter/js/list.js' %}"></script>
{% endblock %}

{% block columns %}
<tr>
    <th scope="col" style="width: 5%">#</th>
    <th scope="col" style="width: 20%">Titulo</th>
    <th scope="col" style="width: 10%">Referência</th>
    <th scope="col" style="width: 10%">Data de envio</th>
    <th scope="col" style="width: 15%">Autor</th>
    <th scope="col" style="width: 7%">Estado</th>
    <th scope="col" style="width: 10%">Opções</th>
</tr>
{% endblock %}

{% block rows %}

{% endblock %}

{% block footer %}

{% endblock %}

{% block js %}
<script src="{% static 'letter/js/list.js' %}"></script>
{% endblock %}

core/erp/templates/letter/my.html
{% extends 'list.html' %}
{% load static %}
{% block  head_list %}

<script src="{% static 'letter/js/mylist.js' %}"></script>
{% endblock %}

{% block columns %}
<tr>
    <th scope="col" style="width: 2%">#</th>
    <th scope="col" style="width: 10%">Referência</th>
    <th scope="col" style="width: 20%">Assunto</th>
    <th scope="col" style="width: 8%">Data de envio</th>
    <th scope="col" style="width: 15%">Autor</th>
    <th scope="col" style="width: 10%">Estado</th>
    <th scope="col" style="width: 10%">Opções</th>
    <input type="text"  visible="false" value="{{manager}}" id="manager" readonly="true" style="visibility: hidden; display:none">
</tr>
{% endblock %}

{% block rows %}

{% endblock %}

    <div class="card-footer">
        {% block footer %}
            <a href="{{ create_url }}" class="btn btn-primary btn-flat btnTest">
                <i class="fas fa-plus"></i> Escrever carta
            </a>

            <a href="{{ list_url }}" class="btn btn-success btn-flat">
                        <i class="fas fa-sync"></i> Actualizar
                    </a>
         {% endblock %}
    </div>

{% block js %}
<script src="{% static 'letter/js/mylist.js' %}">
    var my_chart = {{ manager }};

    console.log(my_chart)
    mi_list({{manager}})
</script>
{% endblock %}

core/erp/templates/letter/pendent.html
{% extends 'list.html' %}
{% load static %}
{% block  head_list %}
<script src="{% static 'absense/js/list.js' %}"></script>
{% endblock %}

{% block columns %}
<tr>
    <th scope="col" style="width: 10%">#</th>
    <th scope="col" style="width: 30%">Motivo</th>
    <th scope="col" style="width: 20%">Colaborador</th>
    <th scope="col" style="width: 20%">Data de Inicio</th>
    <th scope="col" style="width: 10%">Data de Fim</th>
    <th scope="col" style="width: 10%">Dias</th>
    <th scope="col" style="width: 10%">Estado</th>
    <th scope="col" style="width: 10%">Opções</th>
</tr>
{% endblock %}

{% block rows %}

{% endblock %}

{% block js %}
<script src="{% static 'absense/js/list.js' %}"></script>
{% endblock %}

core/erp/templates/letter/search.html
{% extends 'form.html' %}
{% load static %}

{% block head %}
<link href="{% static 'lib/jquery-ui-1.12.1/jquery-ui.min.css' %}" rel="stylesheet"/>
<script src="{% static 'lib/jquery-ui-1.12.1/jquery-ui.min.js' %}"></script>

<link href="{% static 'lib/select2-4.0.13/css/select2.min.css' %}" rel="stylesheet"/>
<link href="{% static 'lib/select2-4.0.13/css/select2-bootstrap4.min.css' %}" rel="stylesheet"/>
<script src="{% static 'lib/select2-4.0.13/js/select2.min.js' %}"></script>
<script src="{% static 'lib/select2-4.0.13/js/i18n/es.js' %}"></script>

<script src="{% static 'lib/moment-2.25.3/moment-with-locales.js' %}"></script>
<script src="{% static 'lib/tempusdominus-bootstrap-4/tempusdominus-bootstrap-4.min.js' %}"></script>
<link href="{% static 'lib/tempusdominus-bootstrap-4/tempusdominus-bootstrap-4.min.css' %}" rel="stylesheet"/>

<link href="{% static 'lib/bootstrap-touchspin-4.3.0/jquery.bootstrap-touchspin.css' %}" rel="stylesheet"/>
<script src="{% static 'lib/bootstrap-touchspin-4.3.0/jquery.bootstrap-touchspin.js' %}"></script>

<link href="{% static 'lib/select2-4.0.13/css/select2.min.css' %}" rel="stylesheet"/>
<link href="{% static 'lib/select2-4.0.13/css/select2-bootstrap4.min.css' %}" rel="stylesheet"/>
<script src="{% static 'lib/select2-4.0.13/js/select2.min.js' %}"></script>
<script src="{% static 'lib/select2-4.0.13/js/i18n/es.js' %}"></script>

<link href="https://cdn.quilljs.com/1.3.7/quill.snow.css" rel="stylesheet">
<link href="{% static 'css/style.css' %}" rel="stylesheet">

{% endblock %}
{% block content %}


<form id="referencia-form" novalidate="novalidate" xmlns="http://www.w3.org/1999/html">

    {% csrf_token %}

    <div class="card card-danger">
        <div class="card-header">
            <h3 class="card-title">Pesquise o código de referência</h3>
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-3">
                    <div class="form-group">

                        <input type="text" class="form-control" id="referencia" name="referencia"
                               placeholder="Digite o Código de Referência" aria-describedby="InputReferencia"
                               aria-invalid="true">
                        <!--                        <span id="InputReferencia-error"-->
                        <!--                              class="error invalid-feedback">Por favor digite um código de referencia.</span>-->
                    </div>

                </div>

                <div class="col-4">
                    <button type="button" class="btn btn-info" id="verificar-btn">Pesquisar</button>
                    <button type="button" class="btn btn-danger" id="anuluar-btn" style="visibility: hidden">Voltar
                    </button>
                </div>

            </div>
<!--            <button type="submit" class="btn btn-success" id="salvar-btn" style="display: ;">Salvar</button>-->
        </div>
    </div>
</form>


<script>
    let fields = document.querySelectorAll('.required');
    $(document).ready(function () {
        $("#verificar-btn").click(function (e) {
            e.preventDefault();

            const referencia = $("#referencia").val();  // Obter o valor do input
            let fields = document.querySelectorAll('.required');
            let spans = document.querySelectorAll('.span-required');
            let allgood = true;

            $.ajax({
                delay: 250,
                url: "{% url 'erp:reference_search' %}",  // Substitua pela URL correta
                method: "POST",
                data: {
                    referencia: referencia,
                    'csrfmiddlewaretoken': "{{ csrf_token }}"
                },
                dataType: "json",
                success: function (response) {
                    if (response.exists) {
                        if (response.associado) {
                            alert("Código de referência já está em uso. Tente com outro código válido.");
                        } else {
                            console.log(response, 'VAZIO');
                            code = document.getElementById("reference_code")
                            //code.value = response.associado;
                             $('body').addClass('fade-out hidden'); // Adiciona a classe para a animação
                    setTimeout(function() {
                        window.location.href = '{% url "erp:letter_create" %}';
                    }, 500); // Tem


                        }

                    } else {
                        alert("Código de referência inválido.");
                    }
                }
            });
        });

    });

</script>
{% endblock %}